### ISSUE TITLE
issues with certain CRS definitions 

### ISSUE THREAD

**Issue by AndrewAnnex** [pole-surfaces-planetaires/planet_crs_registry#7]
I am noticing that CRS codes like 51011 are returning errors. See https://www.opengis.net/def/crs/IAU/2015/51011 vs https://www.opengis.net/def/crs/IAU/2015/51010

**Comment by J-Christophe** [comment]
Thanks Andrew. It seems there are several issues during the GML conversion using GDAL.

**Comment by AndrewAnnex** [comment]
@J-Christophe the newest version of Proj (3.6.0) may resolve some issues that gdal may have with the CRSs

**Comment by J-Christophe** [comment]
Closes with release v1.0.0
